application: luanvanbk2014
version: 2
runtime: php
api_version: 1
threadsafe: false

handlers:
- url: /user_guide
  static_dir: user_guide

- url: /assets/js
  static_dir: assets/js

- url: /assets/css
  static_dir: assets/css

- url: /assets/font
  static_dir: assets/font

- url: /assets/img
  static_dir: assets/img

- url: /assets/avatars
  static_dir: assets/avatars

- url: /assets/images
  static_dir: assets/images

- url: /
  script: index.php

- url: /(.+)
  script: index.php